name = "MetalGtk4Bug"
uuid = "45f45838-0c26-4608-a33e-bea2dff077b3"
authors = ["Nehal Patel <nehal@alum.mit.edu>"]
version = "0.1.0"

[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
FixedPointNumbers = "53c48c17-4a7d-5ca2-90c5-79b7896eea93"
Gtk4 = "9db2cae5-386f-4011-9d63-a5602296539b"
Metal = "dde4c033-4e86-420c-a63e-0dd931031962"
